trigger:
- master

pool:
  name: Default   # Make sure this matches your self-hosted agent pool name

steps:
- script: |
    source venv/bin/activate
    python app.py &
    sleep 10
  displayName: 'Run Flask App'
