trigger:
- master

pool:
  name: Default  # Must match exactly with the pool name where your agent is registered

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    pip install -r requirements.txt
    python app.py
  displayName: 'Install dependencies & run Flask app'
