trigger:
- master

pool:
  name: Default  # Make sure this matches your self-hosted agent pool name

steps:
- script: |
    sudo apt update
    sudo apt install -y python3 python3-pip
    python3 --version
    pip3 install -r requirements.txt
    python3 app.py
  displayName: 'Install Python, dependencies and run app'
