trigger:
- master

pool:
  name: Default   # Make sure this matches your self-hosted agent pool name

steps:
- script: |
    python3 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    python app.py
  displayName: 'Run Flask App'
