containers:
  - name: flask-container
    image: kesavakiran/flask-aks-app:v3
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: flask-secret
            key: SECRET_USERNAME
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: flask-secret
            key: SECRET_PASSWORD
    ports:
    - containerPort: 5000

    envFrom:
    - configMapRef:
        name: flask-config
    - secretRef:
        name: flask-secret

    livenessProbe:
      httpGet:
        path: /
        port: 5000
      initialDelaySeconds: 5
      periodSeconds: 10

    readinessProbe:
      httpGet:
        path: /
        port: 5000
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: flask-disk-volume
      mountPath: /mnt/azure
      name: azure

volumes:
- name: flask-disk-volume
  persistentVolumeClaim:
    claimName: flask-disk-pvc
- name: azure
  azureFile:
    secretName: azure-secret
    shareName: flaskfileshare
    readOnly: false
